<?php
  // Variables
  return [
    "creatorName" => "ThemeSelection",
    "creatorUrl" => "https://localhost",
    "templateName" => "SMMQuest",
    "templateSuffix" => "SMMQuest - User",
    "templateVersion" => "1.0.0",
    "templateFree" => false,
    "templateDescription" => "",
    "templateKeyword" => "",
    "countries" => ["Australia", "Bangladesh", "Belarus", "Brazil", "Canada", "China", "France", "Germany", "India", "Indonesia", "Israel", "Italy", "Japan", "Korea, Republic of", "Latvia", "Mexico", "Philippines", "Russian Federation", "South Africa", "Thailand", "Turkey", "Ukraine", "United Arab Emirates", "United Kingdom", "United States"], 
    "timeZones" => [
      "(GMT-12:00) International Date Line West" => -12,
      "(GMT-11:00) Midway Island, Samoa" => -11,
      "(GMT-10:00) Hawaii" => -10,
      "(GMT-09:00) Alaska" => -9,
      "(GMT-08:00) Pacific Time (US & Canada)" => -8,
      "(GMT-08:00) Tijuana, Baja California" => -8,
      "(GMT-07:00) Arizona" => -7,
      "(GMT-07:00) Chihuahua, La Paz, Mazatlan" => -7,
      "(GMT-07:00) Mountain Time (US & Canada)" => -7,
      "(GMT-06:00) Central America" => -6,
      "(GMT-06:00) Central Time (US & Canada)" => -6,
      "(GMT-06:00) Guadalajara, Mexico City, Monterrey" => -6,
      "(GMT-06:00) Saskatchewan" => -6,
      "(GMT-05:00) Bogota, Lima, Quito, Rio Branco" => -5,
      "(GMT-05:00) Eastern Time (US & Canada)" => -5,
      "(GMT-05:00) Indiana (East)" => -5,
      "(GMT-04:00) Atlantic Time (Canada)" => -4,
      "(GMT-04:00) Caracas, La Paz" => -4,
    ],
    "currencies" => ["USD", "EUR", "INR", "TRY", "RUB", "BRL", "NGN", "KRW", "THB", "SAR", "CNY", "VND", "KWD", "EGP", "PKR", "PHP"],
  ];
